EPSILON                = 1 / 3
MNIST_ROW_SIZE         = 28
MNIST_COL_SIZE         = 28
MNIST_SUBSAMPLE_FACTOR = 40
MNIST_MEAN_VALUE_SCALE = 1.5
MNIST_MIN_CORR_COEFF   = 0.8
SUPPORTED_DATASETS     = ["FEC", "mnist", "mnist_corr"]
